
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

SCREEN_SHAKE_MAX_OFFSET_X = 9
SCREEN_SHAKE_MAX_OFFSET_Y = 9
SCREEN_SHAKE_UNIFORM_X_MOD = 1.14
SCREEN_SHAKE_UNIFORM_Y_MOD = 1.2
SCREEN_SHAKE_JITTER_X_MOD = 7
SCREEN_SHAKE_JITTER_Y_MOD = 12
SCREEN_SHAKE_ASTEROID_SPLIT_LENGTH = 0.85
SCREEN_SHAKE_ASTEROID_SPLIT_INTENSITY = 4.3 * 1.05
SCREEN_SHAKE_ASTEROID_KILL_LENGTH = 0.6
SCREEN_SHAKE_ASTEROID_KILL_INTENSITY = 3.650 * 1.05

SCREEN_BACKGROUND_MODIFIER = - 0.725
GRIDLINE_A_MODIFIER = - 0.7
GRIDLINE_B_MODIFIER = - 0.660
BASE_GLOBAL_HUE = 0.0
BASE_GLOBAL_SAT = 0.775
BASE_GLOBAL_BRIGHTNESS = 0.775

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#ASTEROID_SPLIT_FLASH_LENGTH = 0.8
#ASTEROID_SPLIT_FLASH_INTENSITY = 1.2
#ASTEROID_KILL_FLASH_LENGTH = 0.5325
#ASTEROID_KILL_FLASH_INTENSITY = 1.61


ASTEROID_SPLIT_FLASH_LENGTH = 1.2
ASTEROID_SPLIT_FLASH_INTENSITY = 1.5
ASTEROID_KILL_FLASH_LENGTH = 0.8
ASTEROID_KILL_FLASH_INTENSITY = 1.75


PLAYER_VISIBLE_RADIUS = 20
PLAYER_GHOST_IMAGE_LENGTH = 1.25 # 1.2
PLAYER_GHOST_IMAGE_INTENSITY = 54 # 54
PLAYER_GHOST_IMAGE_FREQUENCY = 0.125
PLAYER_RADIUS = 10
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.2
PLAYER_SHOT_FLASH_LENGTH = 0.36
PLAYER_SHOT_FLASH_INTENSITY = 1.75

SHOT_RADIUS = 5
SHOT_GHOST_IMAGE_LENGTH = 1.1
SHOT_GHOST_IMAGE_INTENSITY = 34 # * 1 #31
SHOT_GHOST_IMAGE_FREQUENCY = 0.385 #0.3725

STAR_SPAWN_RATE = 0.15