SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

SCREEN_SHAKE_MAX_OFFSET_X = 7
SCREEN_SHAKE_MAX_OFFSET_Y = 7
SCREEN_SHAKE_ASTEROID_SPLIT_LENGTH = 0.8
SCREEN_SHAKE_ASTEROID_SPLIT_INTENSITY = 4.5
SCREEN_SHAKE_ASTEROID_KILL_LENGTH = 0.6
SCREEN_SHAKE_ASTEROID_KILL_INTENSITY = 3.5

SCREEN_BACKGROUND_MODIFIER = - 0.725
BASE_GLOBAL_HUE = 0.0
BASE_GLOBAL_SAT = 0.775
BASE_GLOBAL_BRIGHTNESS = 0.775

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_FLASH_LENGTH = 1.2
ASTEROID_SPLIT_FLASH_INTENSITY = 1.5
ASTEROID_KILL_FLASH_LENGTH = 0.8
ASTEROID_KILL_FLASH_INTENSITY = 1.75

PLAYER_RADIUS = 10
PLAYER_VISIBLE_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SHOT_FLASH_LENGTH = 0.36
PLAYER_SHOT_FLASH_INTENSITY = 1.75
SHOT_RADIUS = 5

